### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by bravisSer** [bravisSer/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by bravisSer** [comment]
I'm cool. I conquer everything that moves and that does not move, I move and I win too, so my merch will also give you the opportunity to win.

**Comment by braviserio** [comment]
I'm cool. I conquer everything that moves and that does not move, I move and I win too, so my merch will also give you the opportunity to win.
